import {useSelector} from 'react-redux';
export const useTranslation = () => {
  const textStringEng = {
    productHasBeenDeleted: 'Product details are getting loaded.',
    loginInputemail: 'Job ID / Email / Phone No.',
    loginInputPassword: 'Password',
    loginbtnTxt: 'Login',
    forgotPassword: 'Forgot your password',
    homeMainHeading: 'This screen is only for displaying all screens',
    teamBtnTxt: 'Team',
    dectTeamBtnTxt: 'Dedicated team',
    superBtnTxt: 'Supervisors',
    contactUsSupervisor: 'Supervisor',
    conatactTeamMemberTxt: 'Team Member',
    adminBtnTxt: 'Admin',
    orderTitle: 'Orders',
    currentTitle: 'Current',
    prevoisTitle: 'Previous',
    comingTitle: 'Processing',
    orderIdTitle: 'Order Id',
    singleBattery: 'battery',
    editBtnTxt: 'Edit',
    startDelivery: 'Start Delivery',
    arrivedOnLocation: 'Arrived',
    recivedOrderTxt: 'We received your Order',
    techArrivedTxt: 'The technician arrived at the site',
    orderCompletedTxt: 'Your order is complete',
    quantityTxt: 'Quantity',
    orderTimeTxt: 'Order Time',
    balanceAmount: 'Balance Amount',
    appointmentTxtOrder: 'Appointment Time',
    paymentmode: 'Payment Mode',
    TotalPrice: 'Total Price',
    plateNumberTxt: 'Plate Number',
    phoneNumTxt: 'Phone No.',
    fuelType: 'Fuel Type',
    clientNameTxt: 'Client Name',
    recipiantAddressTxt: 'Recipient address',
    freeServicesTxt: 'Free services',
    freeCarWashTxt: 'Free car and machine wash',
    cashBackTxt: 'Cashback',
    discountCodeTxt: 'Discount code',
    priceCodeTxt: 'Price',
    oldPriceCodeTxt: 'Previous Total Price',
    wagesCodeTxt: 'Service Charges',
    taxCodeTxt: 'Tax',
    totalCodeTxt: 'Total',
    currencyTxt: 'SAR',
    recivedOrderTxtBtn: 'Receive order',
    batteriesTxt: 'Batteries',
    TiresTxt: 'Tires',
    oilAndFilterTxt: 'Oil & Filters',
    enineOilTxt: 'Engine Oil',
    supportServiceTxt: 'Support Services',
    acZurexTxt: 'Ac zurex battery',
    camelTxt: 'Camel battery',
    michlanTireTxt: 'Michelin tire',
    bridgeStoneTireTxt: 'BRIDGESTONE tire',
    oilFilterTxt: 'Oil filter',
    airFilterTxt: 'Air filter',
    acFilter: 'Air conditioner filter',
    freeServiceTitle1: 'Oil Change',
    freeServiceTitle2: 'Other Oils',
    freeServiceTitle3: 'Filters',
    freeServiceTitle4: 'Tires',
    freeServiceTitle5: 'Batteries',
    freeServiceTitle6: 'Support Services',
    addTxtBtn: 'Add',
    balanceBtnTxt: 'Balance',
    contactUsBtnTxt: 'Contact with supervisor',
    AboutUsBtnTxt: 'About Us',
    faqBtnTxt: 'FAQ',
    termsAndConditionBtnTxt: 'Terms and Conditions',
    logoutBtnTxt: 'Logout',
    contactUsAdminBtnTxt: 'Contact with admin',

    termsdataTxt: [
      {
        answer:
          'The store reserves the right to change parts of the terms and conditions of use, modify them, add some of them, or remove them at any time, and the changes become effective when they are published on the store without prior notice, so we hope that you review the terms and conditions periodically to keep abreast of all updates',
        id: 0,
      },
      {
        answer:
          'Your personal data and privacy are kept strictly confidential and are of interest to us',
        id: 1,
      },
      {
        answer:
          'Keep updating your data and information continuously during the purchase process, including your email address, credit card number and dates, so that we can complete your purchases on the store and communicate .With you when you need it',
        id: 2,
      },
      {
        answer:
          'The store has the possibility to withdraw the membership or suspend the account of customers who violate any of the terms of use',
        id: 3,
      },
      {
        answer:
          'A person cannot register as a member of the store more than once',
        id: 4,
      },
      {
        answer:
          'To complete the registration process, you must provide all your contact information',
        id: 5,
      },
      {
        answer: 'The sale only takes place if you accept the terms',
        id: 6,
      },
      {
        answer:
          'Take responsibility for all operations that take place under your account and your password',
        id: 7,
      },
      {
        answer:
          'We strive to provide all information regarding product pricing and to provide an accurate description of each of the products displayed in the store',
        id: 8,
      },
      {
        answer:
          'You may be fully responsible before the competent and judicial authorities if it is proven that you are using a misleading or false e-mail or impersonating another person for the purpose of misleading us so that we do not know the source',
        id: 9,
      },
      {
        answer:
          'Any of your comments or publishing infringing contents, viruses or malware that may harm the store',
        id: 10,
      },
      {
        answer:
          'We have the right, in the event of a violation of any of the previous clauses, to stop your use of the store.',
        id: 11,
      },
    ],

    faqQuestion1: 'What types of batteries do we supply',
    faqAnswer1:
      'We offer all types of ac zurex batteries, made in Malaysia, that last for a full year, as we are the exclusive agent for this brand in the Kingdom of Saudi Arabia.',
    faqQuestion2: 'What about the quality of the batteries',
    faqAnswer2:
      'All products we sell meet the requirements set by the relevant country of Saudi Arabia',
    faqQuestion3: 'Why there is a big difference in prices',
    faqAnswer3:
      'The difference is due to the quality and quality of the batteries.',
    faqQuestion4: 'How can I buy a battery from ac zurex store',
    faqAnswer4:
      'Enter your data on the store, then choose the preferred battery to the cart list, then fill in the payment information, and we will contact you and send the battery to your place with our installation team.',
    faqQuestion5: 'Is the battery under warranty',
    faqAnswer5:
      'Each battery comes with a standard warranty.\nThe warranty is void if the battery is used in the wrong way',
    faqQuestion6: 'Can I buy a battery from you and ship it to my country',
    faqAnswer6:
      'Yes, we can ship a large amount to you via your shipping companies. Please contact us via email or technical support',
    faqQuestion7: 'Is there a refund and replacement',
    filterTypeTxt: 'Type',
    faqAnswer7:
      'There is no return or exchange, but only according to the warranty card that came with the battery',
    faqQuestion8: 'Can my old car battery be replacedwith an ac zurex battery',
    faqAnswer8:
      'Yes, you can replace your battery with a battery from ac zurex with a discount of 30 SAR on a code',
    whatsappTxt: 'Whatsapp',
    instagramTxt: 'Instagram',
    twitterTxt: 'Twiter',
    emailTxt: 'Email',
    mobileTxt: 'Mobile',
    aboutUsQuestion1: 'About Us',
    aboutUsQuestion2: 'Our Service',
    aboutUsQuestion3: 'Our vision',
    aboutUsQuestion4: 'Our goals',
    aboutUsQuestion5: 'Our values',
    aboutUsAnswer1:
      "The ac zurex app is a battery application for Ismail al Jama'an Trading Company, a leader in the field of car batteries and the import of car parts and accessories, at the level of the kingdom of Saudi Arabia, and our activity and services extend to a wide range throughout the kingdom through our branches .It is the exclusive agent of the aczurex brand in the kingdom",
    aboutUsAnswer2:
      "We work at Ismail al Jama'an trading establishment to provide the best types of car batteries, car parts and accessories to all our customers with the required quality, we are one of the leading distributors of various brands of batteries from Korea, Taiwan and Indonesia .Thailand, China, homemade",
    aboutUsAnswer3:
      'The Corporation intends to be the leader in its field in the wholesale and retail trade of auto products, spare parts and accessories, and the sale of high-quality car and truck batteries in the Kingdom, and to achieve its vision through sustainable growth through innovation in development and prosperity with the best international products and the provision of an advanced workforce of engineers and consultants.',
    aboutUsAnswer4:
      'Providing the best quality products and effective after-sales services at the national level, and we are working to develop them in parallel with the local and international markets with high-quality environmentally friendly products and a guaranteeCustomer satisfaction is the goal of our company, and we want to constantly reach and explore global markets',
    aboutUsAnswer5:
      'The real wealth of the company lies in its solid relationshipsWe consider it the cornerstone in the construction and management of our company, which is one of the constants that we do not deviate from, and strives to understand their requirements and needs.',
    btnLess: 'Show Less',
    btnMore: 'More',
    contactUsDescTxt:
      'Contact us on one of these method and we make every effort to respond to your inquiries as soon as possible',
    completedOrderLabelTxt: 'Completed orders',
    unCompletedOrderLabelTxt: 'Uncompleted orders',
    numberOfOrdersTxt: 'Number of order',
    revenueTxt: 'Revenues',
    fromBtnTxt: 'From',
    toBtnTxt: 'To',
    byCarBtnTxt: 'By Car',
    byOrderBtnTxt: 'By Order',
    byCityBtnTxt: 'By City',
    byOrderRevBtnTxt: 'By Order revenue',
    byNeighborHoodBtnTxt: 'By Neighborhood',
    currnetStatusTxt: 'Current',
    newStatusTxt: 'New',
    cancelStatusTxt: 'Cancel',
    deferredStatusTxt: 'Deferrd',
    completedStatusTxt: 'Completed',
    filterTitleTxt: 'Filter',
    applyBtnTxt: 'Apply',
    rateServiceClientTxt: 'Rate the service by the client',
    rateServiceProviderTxt: 'Rate the service provider',
    acceptBtnTxt: 'Accept',
    canecelReasonTxt: 'Reason for cancellation of the order',
    selectDateHeadinTxt: 'Select Date',
    teamsBtnTxtHead: 'Teams',
    servicesMainHeadingTxt: 'Services',
    byBrandTxt: 'By Brand',
    byTypeTxt: 'By Type',
    byTeamTxt: 'By Teams',
    choseTypeOfOilTxt: 'Choose the type of oil',
    choseTypeOfFilterTxt: 'Filter type selection',
    choseTypeOfTireTxt: 'Tire brand selection',
    choseTypeOfOtherOilTxt: 'Choose the type of other oil',
    choseServiceType: 'Service Type',
    choseBatteryType: 'Battery Type',
    orderRevBtnTxt: 'Order revenue',
    numOrdersBtnTxt: 'Number of order',
    superVisorBtnTxtHead: 'Supervisors',
    viewAllBtnTxt: 'View All',
    viewLessBtnTxt: 'View Less',
    yearBtnTxt: 'This year',
    weekBtnTxt: 'This week',
    monthBtnTxt: 'This month',
    todayBtnTxt: 'Today',
    monthPlaceTxt: 'Month',
    revenueBtnTxtHed: 'Revenues',
    teamPerformaanceTxt: 'Team Performance',
    teamEvolutionTxt: 'Team evaluation',
    oilAndBatryChangeTeam: 'Oil and battery change teams',
    cancedOrderTxtHead: 'Canceled',
    teamMembersTxtHead: 'Team members',
    teamSiteBtnNow: 'Team site now',
    mostREqServTxt: 'Most requested services',
    highRatedSupervisor: 'Highest rated supervisors',
    highRatedTeam: 'Highest rated teams',
    homeTxtBtn: 'Home',
    shareBtnWalaTxt: 'SHARE',
    callBtnTxt: 'Call',
    editSccessTxtHead: 'Edit successfully',
    commisonTxtHead: 'Commission',
    contactTeamMemberTxt: 'Contact with team member',
    teamMemberTxtMain: 'Team Member',
    superPerfomTxt: 'Supervisor Performance',
    //djfhdj
    authErrorTitle: 'Auth Error',
    userDontEror: 'User does not exist.Please request admin for one.',
    emailError: 'Please enter your job Id',
    passwordNotError: 'Please enter your password',
    passwordError: 'Wrong Password.Please enter right password',
    loadingTxt: 'Loading...',
    formFillError: 'Please fill all fields',
    noDataFond: 'No products to show',
    logoutAlertMsg: 'Are you sure you want to log out of the account',
    logoutYesTxt: 'Yes, I am sure',
    logoutNoTxt: 'No',
    assignBtnTxt: 'Assign',
    normalEror: 'Error',
    filterTypeNotSelected:
      'Please select the filter type from the options Original or Commercial',
    orignalTxtFilter: 'Original',
    commercialTxtFilter: 'Commercial',
    teamSelctionError: 'Please Select a team from the list.',
    teamMemberSelctionError:
      'Please Select atleast one team member from the team member list.',
    submitModalBtn: 'Submit',
    cancelReasonTxt: 'Reason to cancel',
    enterReasonToCancel: 'Enter reason to cancel the order',
    completTxt: 'Completed',
    cartTxt: 'Cart',
    supervisorEvolutionTxt: 'Supervisor evaluation',
    saveBTnTxt: 'Save',
    editOrderCartAlertMsg:
      'Are you sure you want to add the products in current order',
    openGpsSetting: 'Open GPS Settings',
    gpsDisabled: 'GPS is disabled. Please enable it in settings.',
    locationPermissionDenied:
      'Location permission denied. Please enable it in settings.',
  };
  const textStringArb = {
    penGpsSetting: 'فتح إعدادات GPS',
    gpsDisabled: 'تم تعطيل نظام تحديد المواقع. يرجى تمكينه في الإعدادات.',
    locationPermissionDenied:
      'تم رفض إذن تحديد الموقع. يرجى تمكينه في الإعدادات.',
    productHasBeenDeleted: 'تم حذف المنتج من قبل المشرف.',
    editOrderCartAlertMsg:
      'هل أنت متأكد أنك تريد إضافة المنتجات بالترتيب الحالي؟',
    saveBTnTxt: 'يحفظ',
    teamMemberSelctionError:
      'الرجاء تحديد عضو واحد على الأقل في الفريق من قائمة أعضاء الفريق.',
    supervisorEvolutionTxt: 'تقييم المشرف',
    cartTxt: 'عربة التسوق',
    completTxt: 'مكتمل',
    enterReasonToCancel: 'أدخل السبب لإلغاء الطلب',
    cancelReasonTxt: 'سبب الإلغاء',
    submitModalBtn: 'يُقدِّم',
    teamSelctionError: 'الرجاء اختيار فريق من القائمة.',
    normalEror: 'خطأ',
    filterTypeNotSelected: 'يرجى تحديد نوع الفلتر من الخيارات أصلي أو تجاري',
    orignalTxtFilter: 'إبداعي',
    commercialTxtFilter: 'تجاري',
    assignBtnTxt: 'تعيين',
    logoutNoTxt: 'لا اريد',
    logoutYesTxt: 'نعم أنا متأكد',
    logoutAlertMsg: 'هل أنت متأكد من أنك تريد تسجيل خروج من الحساب',
    noDataFond: 'لا توجد منتجات لعرضها',
    authErrorTitle: 'خطأ في المصادقة',
    userDontEror: 'المستخدم غير موجود.يرجى طلب واحد من المشرف.',
    emailError: 'الرجاء إدخال معرف الوظيفة الخاصة بك',
    passwordNotError: 'من فضلك أدخل رقمك السري',
    passwordError: 'كلمة المرور خاطئة. الرجاء إدخال كلمة المرور الصحيحة',
    loadingTxt: '... تحميل',
    formFillError: 'لو سمحت أملأ كل الحقول',
    superPerfomTxt: 'أداء المشرف',
    teamMemberTxtMain: 'أعضاء الفريق',
    contactTeamMemberTxt: 'تواصل مع عضو الفريق',
    commisonTxtHead: 'عمولة',
    editSccessTxtHead: 'تحرير بنجاح',
    callBtnTxt: 'يتصل',
    shareBtnWalaTxt: 'يشارك',
    homeTxtBtn: 'بيت',
    contactUsAdminBtnTxt: 'تواصل مع المشرف',
    highRatedSupervisor: 'المشرفين الأعلى تقييماً',
    highRatedTeam: 'الفرق الأعلى تقييماً',
    mostREqServTxt: 'معظم الخدمات المطلوبة',
    teamSiteBtnNow: 'موقع الفريق الآن',
    teamMembersTxtHead: 'أعضاء الفريق',
    cancedOrderTxtHead: 'ألغيت',
    oilAndBatryChangeTeam: 'فرق تغيير الزيت والبطارية',
    teamEvolutionTxt: 'تقييم الفريق',
    teamPerformaanceTxt: 'أداء الفريق',
    revenueBtnTxtHed: 'الإيرادات',
    monthPlaceTxt: 'الشهر',
    yearBtnTxt: 'هذا العام',
    weekBtnTxt: 'هذا الاسبوع',
    monthBtnTxt: 'هذا الشهر',
    todayBtnTxt: 'اليوم',
    viewAllBtnTxt: 'مشاهدة الكل',
    viewLessBtnTxt: 'عرض أقل',
    superVisorBtnTxtHead: 'المشرفين',
    orderRevBtnTxt: 'ترتيب الإيرادات',
    numOrdersBtnTxt: 'رقم الطلب',
    choseServiceType: 'نوع الخدمة',
    choseBatteryType: 'نوع البطارية',
    choseTypeOfOilTxt: 'اختر نوع الزيت',
    choseTypeOfFilterTxt: 'اختيار نوع الفلتر',
    choseTypeOfTireTxt: 'اختيار ماركة الإطارات',
    choseTypeOfOtherOilTxt: 'اختر نوع الزيت الآخر',
    byTeamTxt: 'من قبل الفرق',
    byTypeTxt: 'حسب النوع',
    byBrandTxt: 'حسب العلامة التجارية',
    servicesMainHeadingTxt: 'خدمات',
    teamsBtnTxtHead: 'فرق',
    selectDateHeadinTxt: 'حدد تاريخ',
    canecelReasonTxt: 'سبب إلغاء الطلب',
    acceptBtnTxt: 'يقبل',
    rateServiceClientTxt: 'قيم الخدمة من قبل العميل',
    rateServiceProviderTxt: 'قيم مزود الخدمة',
    applyBtnTxt: 'تطبيق',
    filterTitleTxt: 'منقي',
    currnetStatusTxt: 'حاضِر',
    newStatusTxt: 'جديد',
    cancelStatusTxt: 'يلغي',
    deferredStatusTxt: 'مؤجلة',
    completedStatusTxt: 'مكتمل',
    byCarBtnTxt: 'بواسطة السيارة',
    byOrderBtnTxt: ' بواسطةالطلب',
    byCityBtnTxt: 'حسب المدينة',
    byOrderRevBtnTxt: 'حسب إيرادات النظام',
    byNeighborHoodBtnTxt: 'حسب الحي',
    fromBtnTxt: 'من',
    toBtnTxt: 'إلى',
    numberOfOrdersTxt: 'عدد الطلبات',
    revenueTxt: 'الإيرادات',
    completedOrderLabelTxt: 'الطلبات المكتملة',
    unCompletedOrderLabelTxt: 'أوامر غير مكتملة',
    loginInputemail: 'معرف الوظيفة / البريد الإلكتروني / رقم الهاتف',
    loginInputPassword: 'كلمة المرور',
    loginbtnTxt: 'تسجيل دخول',
    forgotPassword: 'نسيت كلمة السر',
    homeMainHeading: 'هذه الشاشة مخصصة لعرض جميع الشاشات فقط',
    teamBtnTxt: 'فريق',
    dectTeamBtnTxt: 'فريق متخصص',
    contactUsSupervisor: 'المشرف',
    superBtnTxt: 'المشرفين',
    conatactTeamMemberTxt: 'عضو الفريق',
    adminBtnTxt: 'مسؤل',
    orderTitle: 'طلبات',
    currentTitle: 'حاضِر',
    prevoisTitle: 'سابق',
    comingTitle: 'يعالج',
    orderIdTitle: 'رقم الطلب',
    singleBattery: 'بطارية',
    editBtnTxt: 'يحرر',
    startDelivery: 'ابدأ التسليم',
    arrivedOnLocation: 'وصل',
    recivedOrderTxt: 'لقد تلقينا طلبك',
    techArrivedTxt: 'وصل الفني إلى الموقع',
    orderCompletedTxt: 'تم اكتمال طلبك',
    quantityTxt: 'كمية',
    orderTimeTxt: 'وقت الطلب',
    appointmentTxtOrder: 'وقت الموعد',
    plateNumberTxt: 'رقم لوحة',
    phoneNumTxt: 'رقم الهاتف.',
    clientNameTxt: 'اسم العميل',
    recipiantAddressTxt: 'عنوان المستلم',
    freeServicesTxt: 'خدمات مجانية',
    freeCarWashTxt: 'غسيل سيارات وغسيل آلي مجانًا',
    cashBackTxt: 'الكاش باك',
    discountCodeTxt: 'كود الخصم',
    priceCodeTxt: 'السعر',
    oldPriceCodeTxt: 'السعر الإجمالي السابق',
    wagesCodeTxt: 'رسوم الخدمات',
    taxCodeTxt: 'الضريبة',
    totalCodeTxt: 'الإجمالي',
    currencyTxt: 'ر.س',
    recivedOrderTxtBtn: 'إستقبال الأوامر',
    batteriesTxt: 'البطاريات',
    TiresTxt: 'الاطارات',
    oilAndFilterTxt: 'الزيت والفلاتر',
    enineOilTxt: 'زيت المحرك',
    supportServiceTxt: 'الخدمات المساندة',
    acZurexTxt: 'بطارية ايه سي زيوركس',
    camelTxt: 'بطارية كمل',
    michlanTireTxt: 'اطار ميشلان',
    bridgeStoneTireTxt: 'اطار بريدجستون',
    oilFilterTxt: 'زيت فلاتر',
    airFilterTxt: 'هواء فلاتر',
    acFilter: 'فلتر مكيف',
    freeServiceTitle1: 'تغيير زيت',
    freeServiceTitle2: 'زيوت أخرى',
    freeServiceTitle3: 'الفلاتر',
    freeServiceTitle4: 'الاطارات',
    freeServiceTitle5: 'البطاريات',
    freeServiceTitle6: 'الخدمات المساندة',
    addTxtBtn: 'إضافة',
    balanceBtnTxt: 'الرصيد',
    contactUsBtnTxt: 'تواصل مع المشرف',
    AboutUsBtnTxt: 'من نحن',
    faqBtnTxt: 'الأسئلة الشائعة',
    termsAndConditionBtnTxt: 'الشروط والأحكام',
    logoutBtnTxt: 'تسجيل خروج',

    aboutUsQuestion1: 'من نحن',

    aboutUsAnswer1:
      'تطبيق اي سي زيوركس هو تطبيق للبطاريات خاص بمؤسسة إسماعيل الجمعان التجارية، الرائدة  في مجال بطاريات السيارات  واستيراد  قطع غيار  السيارات وملحقاتها، على مستوى المملكة العربية  السعودية،  ويتخطى نشاطنا وخدماتنا إلى نطاق  ،واسع في جميع أنحاء المملكة من خلال فروعنا .وهي الوكيل الحصري لماركة aczurex في المملكة',

    aboutUsQuestion2: 'خدماتنا',
    aboutUsAnswer2:
      'نعمل في مؤسسة إسماعيل الجمعان التجارية على توفير أفضل أنواع بطاريات السيارات وقطع  غيار السيارات وملحقاتها لكافة عملاؤنا بالجودة  المطلوبة، نحن أحد الموزعين الرائدين لمختلف  ماركات البطاريات من كوريا وتايوان وإندونيسيا .وتايلاند والصين والمحلية الصنع',

    aboutUsQuestion3: 'رؤيتنا',
    aboutUsAnswer3:
      'تعتزم المؤسسة أن تكون الرائدة في مجالها بتجارة الجملة و تجزئة منتجات السيارات وقطع غيارها وملحقاتها .وبيع بطاريات السيارات والشاحنات بجودة عالية على مستوى المملكة، وتحقيق رؤيتها من خلال النمو المستدام بالإبتكار في التطوير والإزدهار بأفضل المنتجات العالمية وتوفير قوة عاملة متطورة من المهندسين والإستشاريين',

    aboutUsQuestion4: 'أهدافنا',
    aboutUsAnswer4:
      'تقديم أفضل المنتجات عالية الجودة وخدمات ما بعد البيع الفعالة على الصعيد الوطني ونعمل على ،تطويرها بالتوازي مع الأسواق المحلية والدولية مع منتجات عالية الجودة صديقة للبيئة وضمان  رضا العملاء هو أهداف شركتنا، نحن نرغب في الوصول واستكشاف الأسواق العالمية باستمرار ',

    aboutUsQuestion5: 'Our Values ',
    aboutUsAnswer5:
      ' تكمن الثروة الحقيقية للشركة في علاقاتها المتينة وتعمل على توطيد علاقاتها بهم، ونعتبرها حجر  الأساس فى بناء و إدارة شركتنا وهي من الثوابت  التى لا نحيد عنه ، وتسعى جاهدة لفهم متطلباتهم  واحتياجاتهم',
    btnLess: 'تظهر أقل',
    btnMore: 'المزيد',
    termsdataTxt: [
      {
        answer:
          ' يحتفظ المتجر بالحق في تغيير أجزاء من شروط الاستخدام والأحكام أو تعديلها أو إضافة البعض منها، أو إزالتها في أي وقت من الأوقات، وتصبح التغييرات فعالة عندما يتم نشرها على المتجر من دون سابق إنذار، لذا نأمل منك مراجعة الشروط و الأحكام بشكل دوري لمواكبة كل التحديثات ',
        id: 0,
      },
      {
        answer: 'بياناتك الشخصية وخصوصياتك لدينا في سرية تامة وهي محل اهتمامنا',
        id: 1,
      },
      {
        answer:
          'المداومة على تحديث بياناتك ومعلوماتك بشكل   مستمر أثناء عملية الشراء بما فيها عنوان البريد   ورقم بطاقتك الائتمانية وتواريخها حتى نستطيع  استكمال عملياتك الشرائية على المتجر والتواصل  .معك عند الحاجة لذلك',
        id: 2,
      },
      {
        answer:
          ' المتجر له الحق أن يقوم بسحب عضوية أو تعليق  حساب العملاء المخالفين لأي بند من بنود الإستخدام',
        id: 3,
      },
      {
        answer: 'لا يحق لأي شخص أن يقوم بالتسجيل كعضو في المتجر أكثر من مرة  ',
        id: 4,
      },
      {
        answer:
          'لإتمام عملية التسجيل لابد من توفير كافة معلومات الاتصال الخاصة بك',
        id: 5,
      },
      {
        answer: 'لا تتم عملية البيع إلا في حالة قبولك للشروط ',
        id: 6,
      },
      {
        answer:
          'الموافقة على تقبل المسئولية عن جميع العمليات  .التي تتم تحت الحساب الخاص بك ورقمك السري',
        id: 7,
      },
      {
        answer:
          ' نسعى جاهدين لتوفير كافة المعلومات بشأن تسعير المنتجات وتوفير وصف دقيق عن كل منتج  .من المنتجات المعروضة في المتجر',
        id: 8,
      },
      {
        answer:
          'قد تكون مسئول مسئولية كاملة أمام الجهات المختصة والقضائية حال ثبت أنك تستخدم بريد الكتروني مضلل أو زائف أو تنتحل شخصية أخرى بغرض التضليل لنا حتى لا نعرف مصدر',
        id: 9,
      },
      {
        answer:
          'أي من تعليقاتك أو تقوم بنشر محتويات مخالفة  أو فيروسات أو برمجيات خبيثة قد تضر بالمتجر',
        id: 10,
      },
      {
        answer:
          'فإنه يحق لنا في حال انتهاكك لأي بند من البنود  السابقة إيقاف استخدامك للمتجر',
        id: 11,
      },
    ],

    faqQuestion1: 'ما أنواع البطاريات التي نوفرها؟',
    faqAnswer1:
      'نحن نقدم جميع أنواع بطاريات أي سي زيوركس صناعة ماليزية تدوم لمدة عام كامل حيث أننا  أننا الوكيل الحصري لهذه الماركة في المملكة العربية السعودية  ',
    faqQuestion2: 'ماذا عن جودة البطاريات؟',
    faqAnswer2:
      'جميع المنتجات التي نبيعها تلبي المتطلبات التي وضعتها دولة المملكة العربية السعودية ذات الصلة  ',
    faqQuestion3: 'لماذا يوجد اختلاف كبير في الأسعار؟',
    faqAnswer3: 'الفرق يرجع إلى جودة ونوعية البطاريات',
    faqQuestion4: 'كيف يمكنني شراء بطارية من متجراي سي زيوركس؟',
    faqAnswer4:
      'قم بدخول بياناتك على المتجر ثم اختار البطارية المفضلة إلى قائمة السلة ثم قم بتعبئة بيانات  الدفع وسيتم التواصل معك وارسال البطارية إلىمكانك مع فريق التركيب الخاص بنا ',
    faqQuestion5: 'هل البطارية تحت الضمان؟',
    faqAnswer5:
      '.تأتي كل بطارية مع ضمان قياسي  الضمان باطل إذا تم استخدام البطارية بطريقة غير مستحسنة ',
    faqQuestion6: 'هل يمكنني شراء بطارية منكم وشحنها إلى دولتي؟',
    faqAnswer6:
      'نعم يمكننا شحن لك كمية كبيرة عبر شركات الشحن الخاص بك ارجو تواصل معنا عبر البريد الالكتروني أو الدعم الفني',
    faqQuestion7: 'هل يوجد استرجاع واستبدال؟',
    filterTypeTxt: 'يكتب',
    faqAnswer7:
      'لا يوجد استرجاع واستبدال كرت الضمان المرفق مع البطارية ، لكن فقط حسب',
    faqQuestion8: 'هل يمكن استبدال بطارية سيارتي القديمة ببطارية اي سي زيوركس؟',
    faqAnswer8:
      'نعم، يمكنك استبدال بطاريتك ببطارية من اي سي زيوركس مع خصم 30 ريال على كود',
    whatsappTxt: 'الواتس اب',
    instagramTxt: 'انستاغرام',
    twitterTxt: 'تويتر',
    emailTxt: 'البريد الالكتروني',
    mobileTxt: 'الموبايل',
    contactUsDescTxt:
      ' اتصل بنا بإحدى هذه الطرق وسنبذل قصارى جهدنا للرد على استفساراتك في أسرع وقت ممكن',
  };
  const {isArabicLanguage} = useSelector(state => state.auth);
  const textStrings = isArabicLanguage ? textStringArb : textStringEng;

  return {textStrings};
};
